import { Elysia, InternalServerError, t } from "elysia"
import * as service from "../services"
import { SyncType, syncResponse } from "../commons/types"

const routeController = (app: Elysia) =>
  app.group("/route", (app) => {
    app.get(
      "/:trainId",
      async (ctx) => {
        if (ctx.query.from_station_id)
          return await service.route.getAllFrom(
            ctx.params.trainId,
            ctx.query.from_station_id.toLocaleUpperCase(),
          )
        return await service.route.getAll(ctx.params.trainId)
      },
      {
        params: t.Object({
          trainId: t.String(),
        }),
        query: t.Object({
          from_station_id: t.Optional(t.String()),
        }),
        response: {
          404: t.Object(
            {
              status: t.Number(),
              message: t.String(),
            },
            {
              default: {
                status: 404,
                message: "Route data is not found",
              },
            },
          ),
          200: t.Object(
            {
              status: t.Number(),
              data: t.Array(
                t.Object({
                  id: t.Nullable(t.String()),
                  stationId: t.Nullable(t.String()),
                  stationName: t.Nullable(t.String()),
                  trainId: t.Nullable(t.String()),
                  line: t.Nullable(t.String()),
                  route: t.Nullable(t.String()),
                  color: t.Nullable(t.String()),
                  destination: t.Nullable(t.String()),
                  timeEstimated: t.Nullable(t.String()),
                  destinationTime: t.Nullable(t.String()),
                  updatedAt: t.Nullable(t.String()),
                }),
              ),
            },
            {
              default: {
                status: 200,
                data: [
                  {
                    id: "BKS-5171",
                    stationId: "BKS",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "21:47:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:08.132Z",
                    stationName: "BEKASI",
                  },
                  {
                    id: "KRI-5171",
                    stationId: "KRI",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "21:50:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:14.794Z",
                    stationName: "KRANJI",
                  },
                  {
                    id: "CUK-5171",
                    stationId: "CUK",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "21:56:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:10.959Z",
                    stationName: "CAKUNG",
                  },
                  {
                    id: "KLDB-5171",
                    stationId: "KLDB",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "21:58:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:14.141Z",
                    stationName: "KLENDERBARU",
                  },
                  {
                    id: "BUA-5171",
                    stationId: "BUA",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "21:59:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:08.931Z",
                    stationName: "BUARAN",
                  },
                  {
                    id: "KLD-5171",
                    stationId: "KLD",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "22:01:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:14.080Z",
                    stationName: "KLENDER",
                  },
                  {
                    id: "JNG-5171",
                    stationId: "JNG",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "22:10:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:13.396Z",
                    stationName: "JATINEGARA",
                  },
                  {
                    id: "MTR-5171",
                    stationId: "MTR",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "22:12:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:10.858Z",
                    stationName: "MATRAMAN",
                  },
                  {
                    id: "MRI-5171",
                    stationId: "MRI",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "22:18:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:15.636Z",
                    stationName: "MANGGARAI",
                  },
                  {
                    id: "SUD-5171",
                    stationId: "SUD",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "22:22:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:18.281Z",
                    stationName: "SUDIRMAN",
                  },
                  {
                    id: "SUDB-5171",
                    stationId: "SUDB",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "22:23:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:11.019Z",
                    stationName: "SUDIRMAN BARU",
                  },
                  {
                    id: "KAT-5171",
                    stationId: "KAT",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "22:24:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:13.317Z",
                    stationName: "KARET",
                  },
                  {
                    id: "THB-5171",
                    stationId: "THB",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "22:30:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:18.884Z",
                    stationName: "TANAHABANG",
                  },
                  {
                    id: "DU-5171",
                    stationId: "DU",
                    trainId: "5171",
                    line: "COMMUTER LINE CIKARANG",
                    route: "BEKASI-ANGKE",
                    color: "#0084D8",
                    destination: "ANGKE",
                    timeEstimated: "22:38:00",
                    destinationTime: "22:41:00",
                    updatedAt: "2024-03-16T17:00:12.541Z",
                    stationName: "DURI",
                  },
                ],
              },
            },
          ),
        },

        detail: {
          description:
            "Get a list of schedule data for a train route from a train ID sorted by timeEstimated",
          tags: ["Route"],
        },
      },
    )

    return app
  })

export default routeController
